#spring.application.name=fswd-sbapp

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mn200501
    driver-class-name: org.postgresql.Driver
  application:
    name : fswd-sbapp
  profiles:
    active: dev
server:
#  port : 8090
  servlet:
    context-path: /istad


